/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.HoadonphongDAO;
import Model.HoadonphongModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author phamd
 */
public class HoadonphongView extends javax.swing.JFrame {

    int selectedIndex;
    public int edit;
    int delete;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private List<HoadonphongModel> quanlyhoadonphong;
    private List<HoadonphongModel> tkquanlyhoadonphong;
    private List<HoadonphongModel> checkmahoadonphong;
    private DefaultTableModel model;
    
    
    /**
     * Creates new form HoadonphongView
     */
    public HoadonphongView() {
        initComponents();
        this.setLocationRelativeTo(null);
        model=(DefaultTableModel)Banghienthi.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTimkiem = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Banghienthi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMahdp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMasv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgaylap = new javax.swing.JTextField();
        txtDatra = new javax.swing.JTextField();
        txtConno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTienphong = new javax.swing.JTextField();
        btnThanhtoan = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(214, 217, 223));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnTimkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimkiem)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Danh sách hóa đơn phòng");

        Banghienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Mã hợp đồng", "Mã sinh viên", "Ngày lập", "Tiền phòng", "Đã trả", "Còn nợ"
            }
        ));
        Banghienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanghienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Banghienthi);

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        jLabel2.setText("Mã hóa đơn:");

        jLabel3.setText("Mã Hợp đồng:");

        jLabel6.setText("Mã sinh viên");

        jLabel7.setText("Ngày lập:");

        jLabel9.setText("Đã trả:");

        jLabel10.setText("Còn nợ:");

        txtDatra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatraKeyTyped(evt);
            }
        });

        jLabel8.setText("Tiền phòng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMahd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtMahdp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMasv))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgaylap)
                            .addComponent(txtDatra)
                            .addComponent(txtConno, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTienphong, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGap(483, 483, 483))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMahdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtTienphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(txtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDatra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtConno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit.png"))); // NOI18N
        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        btnGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit.png"))); // NOI18N
        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnLammoi)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat)
                    .addComponent(btnThanhtoan)
                    .addComponent(btnGhi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int thoat = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thoát không?");
                if (thoat == JOptionPane.YES_OPTION) {
                    this.dispose();
                    TrangchuView trangchuView=new TrangchuView();
                    trangchuView.show();
                }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       KhoaMo(false);
        TuTaoMa();
        
        txtMahd.setText("");
   
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        
        String tkhdp=txtTimkiem.getText();

             
                 tkquanlyhoadonphong=new  HoadonphongDAO().Timkiem(tkhdp);
                
                 model.setRowCount(0);
                 DateFormat dateFormat = null;
                 dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                 for(HoadonphongModel s:tkquanlyhoadonphong){
                        model.addRow(new Object[]{
                       Banghienthi.getRowCount()+1,s.getMahdp(),s.getMahd(),s.getMasv(),dateFormat.format(s.getNgaylaphdp()),s.getTienphong(),s.getDatra(),s.getConno(),
                     });
                 }
        
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        KhoaMo(true); 
        XoaTrang();
         
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
       
         txtMahdp.setEditable(true);
        delete=Banghienthi.getSelectedRow();
        HoadonphongModel s=quanlyhoadonphong.get(selectedIndex);
        if (quanlyhoadonphong.size() > 0) {
            if (delete!= -1) {
                int choic = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa?");
                if (choic == JOptionPane.YES_OPTION) {
                    new HoadonphongDAO().Xoahoadonphong(s.getMahdp());
                    showTable();
                    XoaTrang();
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã hủy");
                    XoaTrang();
                    showTable();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sách cần xóa");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void BanghienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanghienthiMouseClicked
        // TODO add your handling code here:
        KhoaMo(true);
        txtMahdp.setEditable(false);
        selectedIndex=Banghienthi.getSelectedRow();
        HoadonphongModel s= quanlyhoadonphong.get(selectedIndex);
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtMahdp.setText(s.getMahdp());
        txtMahd.setText(s.getMahd());
        txtMasv.setText(s.getMasv());
        txtNgaylap.setText(dateFormat.format(s.getNgaylaphdp()));
        txtTienphong.setText(Math.round(s.getTienphong())+"");
        txtConno.setText(Math.round(s.getConno())+"");
        txtDatra.setText(Math.round(s.getDatra())+"");
    
    }//GEN-LAST:event_BanghienthiMouseClicked

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        // TODO add your handling code here:
        double cn =0;
        txtMahdp.setEditable(true);
        edit = Banghienthi.getSelectedRow();
        HoadonphongModel s = quanlyhoadonphong.get(selectedIndex);
        if (quanlyhoadonphong.size() > 0) {
            if (edit != -1) {
           
                        s.setDatra(s.getTienphong());
                        s.setConno(cn);
                        
                            new HoadonphongDAO().Thanhtoan(s);
                            showTable();
                            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
                            XoaTrang();
                      
    
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sách cần thanh toán");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
        
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(txtMahd.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã Hợp đồng");
            txtMahd.requestFocus();
            return;
        }else
        if(txtNgaylap.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày lập");
            txtNgaylap.requestFocus();
            return;
        }else
        if(txtDatra.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nhận số điện");
            txtDatra.requestFocus();
            return;
        }else{

            try {
                HoadonphongModel s=new HoadonphongModel();
                Date dateNow = new Date();
                Date d;
                d = df.parse(txtNgaylap.getText());
                if(d.getTime() <= dateNow.getTime()){
                    s.setMahdp(txtMahdp.getText());
                    s.setMahd(txtMahd.getText());

                    s.setNgaylaphdp(d);
                    boolean isNXB=true;

                    try {
                        s.setDatra(Integer.parseInt(txtDatra.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Đã trả là số ko phải là kí tự");
                        txtDatra.requestFocus();
                        isNXB=false;
                        return;
                    }
                    s.setConno(s.getTienphong()-s.getDatra());

                    checkmahoadonphong=new HoadonphongDAO().CheckMahdp(txtMahdp.getText());
                    System.out.println("ArrayList: " + checkmahoadonphong);
                    System.err.println(tkquanlyhoadonphong);
                    int size = checkmahoadonphong.size();
                    if(size== 0){
                        new HoadonphongDAO().Themhoadonphong(s);
                        showTable();
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        XoaTrang();
                        KhoaMo(true);
                    }
                }else{

                    JOptionPane.showMessageDialog(rootPane, "Ngày lập phải nhỏ hơn hoặc bằng ngày hiện thời!");
                }

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng (vd: dd/MM/yyyy)!");

            }

        }
    }//GEN-LAST:event_btnGhiActionPerformed
/*
    private void txtDatraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatraKeyTyped
            // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDatraKeyTyped
*/                                    
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoadonphongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoadonphongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoadonphongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoadonphongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoadonphongView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Banghienthi;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtConno;
    private javax.swing.JTextField txtDatra;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMahdp;
    private javax.swing.JTextField txtMasv;
    private javax.swing.JTextField txtNgaylap;
    private javax.swing.JTextField txtTienphong;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
    
    private void showTable() {
     quanlyhoadonphong=new HoadonphongDAO().getListHoadonphong();
     model.setRowCount(0);
    DateFormat dateFormat = null;
    dateFormat = new SimpleDateFormat("dd/MM/yyyy");
     for(HoadonphongModel s:quanlyhoadonphong){
          System.err.println(s);
         model.addRow(new Object[]{
             Banghienthi.getRowCount()+1,s.getMahdp(),s.getMahd(),s.getMasv(),dateFormat.format(s.getNgaylaphdp()),s.getTienphong(),s.getDatra(),s.getConno()
        });
         
     }
    
    }
    private void XoaTrang(){
        txtMahdp.setText("");
        txtMahd.setText("");
        txtMasv.setText("");
        txtTienphong.setText("");
        txtNgaylap.setText("");
        txtDatra.setText("");
         txtConno.setText("");
         txtTimkiem.setText("");
        showTable();
    }
    private  void TuTaoMa(){
        String m= HoadonphongDAO.Taoma("hoadonphong", "Mahdp");
        
        try {
            int matt=  Integer.parseInt(m);      
            txtMahdp.setText(String.format("%06d", matt + 1));
        } catch(NumberFormatException e) {
            System.out.println("Khong the chuyen doi chuoi thanh so nguyen");
        }
    }
    public void KhoaMo(boolean b) {
        btnThem.setEnabled(b);
        btnGhi.setEnabled(!b);
        txtMasv.setEnabled(b);
        txtTienphong.setEnabled(b);
        txtConno.setEnabled(b);
        
    }
     private void TinhTien(){
        double tienphong;
        double datra;
        double conno;
        HoadonphongModel s = new HoadonphongModel();
        tienphong= s.getTienphong();
        datra= Double.parseDouble(txtDatra.getText());
        conno= tienphong-datra;  
        s.setConno(conno);
     }
}
