/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.HoadondichvuDAO;
import Model.HoadondichvuModel;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author 
 */
public class HoadondichvuView extends javax.swing.JFrame {

    
    int selectedIndex;
    public int edit;
    int delete;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private List<HoadondichvuModel> quanlyhoadondichvu;
    private List<HoadondichvuModel> tkquanlyhoadondichvu;
    private List<HoadondichvuModel> checkmahoadon;
    private DefaultTableModel model;
    
    
    
    public HoadondichvuView() {
        initComponents();
        this.setLocationRelativeTo(null);
         model=(DefaultTableModel)Banghienthi.getModel();
        showTable();
        txtSodien.setText(0+"");
        txtSonuoc.setText(0+"");
        txtMang.setText(0+"");
        txtTiengiam.setText(0+"");
        txtThanhtien.setText(0+"");
        txtTiendong.setText(0+"");
        txtConno.setText(0+"");
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTimkiem = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Banghienthi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaphong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgaylap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSodien = new javax.swing.JTextField();
        txtSonuoc = new javax.swing.JTextField();
        txtMang = new javax.swing.JTextField();
        jRadioyes = new javax.swing.JRadioButton();
        jRadiono = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtThanhtien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTiengiam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtConno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTiendong = new javax.swing.JTextField();
        btnLammoi = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(214, 217, 223));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnTimkiem)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnTimkiem))
        );

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Danh sách hóa đơn dịch vụ");

        Banghienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Phòng", "Ngày lập", "Số điện", "Số nước", "Mạng", "Tiền giảm", "Thành tiền", "Còn nợ", "Tình Trạng"
            }
        ));
        Banghienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanghienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Banghienthi);

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã hóa đơn:");

        txtMahd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Phòng:");

        txtMaphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày lập:");

        txtNgaylap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số điện:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số nước:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tiền internet:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tình trạng:");

        txtSodien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSodien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSodienKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSodienKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSodienKeyTyped(evt);
            }
        });

        txtSonuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSonuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSonuocKeyReleased(evt);
            }
        });

        txtMang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMangKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioyes);
        jRadioyes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioyes.setText("Đã thanh toán");

        buttonGroup1.add(jRadiono);
        jRadiono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadiono.setText("Chưa thanh toán");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Thành tiền:");

        txtThanhtien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tiền Giảm:");

        txtTiengiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTiengiam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTiengiamKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Còn nợ:");

        txtConno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Đóng tiền:");

        txtTiendong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTiendong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTiendongKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaphong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtMahd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaylap)
                            .addComponent(txtSodien)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSonuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMang)
                            .addComponent(txtTiengiam)
                            .addComponent(txtThanhtien)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadiono))
                            .addComponent(txtConno)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTiendong, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(txtMang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTiengiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSodien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTiendong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jRadioyes)
                            .addComponent(jRadiono)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtConno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSonuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-arrow.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnGhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit.png"))); // NOI18N
        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGhi)
                .addGap(43, 43, 43)
                .addComponent(btnLammoi)
                .addGap(117, 117, 117)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        KhoaMo(false);
        TuTaoMa();
        
        txtMaphong.setText("");
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        XoaTrang();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void BanghienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanghienthiMouseClicked
        // TODO add your handling code here:
        KhoaMo(true);
        txtMahd.setEditable(false);
        selectedIndex=Banghienthi.getSelectedRow();
        HoadondichvuModel s= quanlyhoadondichvu.get(selectedIndex);
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtMahd.setText(s.getMahd());
        txtMaphong.setText(s.getMaphong());     
        txtNgaylap.setText(dateFormat.format(s.getNgaylap()));
        
        txtSodien.setText(s.getSodien()+"");
        txtSonuoc.setText(s.getSonuoc()+"");
        txtMang.setText(s.getMang()+"");
        txtTiengiam.setText(Math.round(s.getTiengiam())+"");
        txtThanhtien.setText(Math.round(s.getThanhtien())+"");
        txtConno.setText(Math.round(s.getConno())+"");
        String tt=s.getTinhtranghd();
        if(tt.equals("Chưa thanh toán")){
            jRadiono.setSelected(true);
        }else{
            jRadioyes.setSelected(true);
        }
        
    }//GEN-LAST:event_BanghienthiMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int thoat = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thoát không?");
                if (thoat == JOptionPane.YES_OPTION) {
                    this.dispose();
                    TrangchuView trangchuView=new TrangchuView();
                    trangchuView.show();
                }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        txtMahd.setEditable(true);
        delete=Banghienthi.getSelectedRow();
         HoadondichvuModel s=quanlyhoadondichvu.get(selectedIndex);
        if (quanlyhoadondichvu.size() > 0) {
            if (delete!= -1) {
                int choic = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa?");
                if (choic == JOptionPane.YES_OPTION) {
                    new HoadondichvuDAO().XoaHoadon(s.getMahd());
                    showTable();
                    XoaTrang();
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã hủy");
                    XoaTrang();
                    showTable();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hóa đơn cần xóa");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        String tkhd=txtTimkiem.getText();

             
                 tkquanlyhoadondichvu=new HoadondichvuDAO().Timkiem(tkhd);
                
                 model.setRowCount(0);
                 DateFormat dateFormat = null;
                 dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                 for(HoadondichvuModel s:tkquanlyhoadondichvu){
                        model.addRow(new Object[]{
                       Banghienthi.getRowCount()+1,s.getMahd(),s.getMaphong(),dateFormat.format(s.getNgaylap()),s.getSodien(),s.getSonuoc(),s.getMang(),s.getTiengiam(),s.getThanhtien(),s.getConno(),s.getTinhtranghd()
                     });
                 }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void txtSodienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodienKeyTyped
        // TODO add your handling code here:
     
      
        
        
    }//GEN-LAST:event_txtSodienKeyTyped

    private void txtSodienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodienKeyPressed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtSodienKeyPressed

    private void txtSodienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSodienKeyReleased
        // TODO add your handling code here:
        TinhTien();
    }//GEN-LAST:event_txtSodienKeyReleased

    private void txtSonuocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSonuocKeyReleased
        // TODO add your handling code here:
        TinhTien();
    }//GEN-LAST:event_txtSonuocKeyReleased

    private void txtMangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMangKeyReleased
        // TODO add your handling code here:
        TinhTien();
    }//GEN-LAST:event_txtMangKeyReleased

    private void txtTiengiamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiengiamKeyReleased
        // TODO add your handling code here:
        TinhTien();
    }//GEN-LAST:event_txtTiengiamKeyReleased

    private void txtTiendongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiendongKeyReleased
        // TODO add your handling code here:
        TinhTien();
    }//GEN-LAST:event_txtTiendongKeyReleased

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        TinhTien();
        if(txtMahd.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã hóa đơn");
            txtMahd.requestFocus();
              return;
        }else
        if(txtMaphong.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập phòng");
            txtMahd.requestFocus();
              return;
        }else
        if(txtNgaylap.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày lập");
            txtMahd.requestFocus();
              return;
        }else
        if(txtSodien.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nhận số điện");
            txtMahd.requestFocus();
              return;
        }else
        if(txtSonuoc.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nhận số nước");
            txtMahd.requestFocus();
              return;
        }else
        if(txtMang.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nhận số mạng");
            txtMahd.requestFocus();
              return;
        }else
        if(txtTiengiam.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập nhận tiền giảm");
            txtMahd.requestFocus();
              return;
        }else{

            try {
                HoadondichvuModel s=new HoadondichvuModel();
                Date dateNow = new Date();
                Date d;
                d = df.parse(txtNgaylap.getText());
                if(d.getTime() <= dateNow.getTime()){
                    s.setMahd(txtMahd.getText());                 
                    s.setMaphong(txtMaphong.getText());
                  
                    s.setNgaylap(d);
                    boolean isNXB=true;
                    
                    try {
                        s.setSodien(Integer.parseInt(txtSodien.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Số điện chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    try {
                        s.setSonuoc(Integer.parseInt(txtSonuoc.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Số nước chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    try {
                        s.setSonuoc(Integer.parseInt(txtSonuoc.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Số nước chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    s.setSonuoc(Integer.parseInt(txtSonuoc.getText()));
                    try {
                        s.setMang(Integer.parseInt(txtMang.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Mạng chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    
                    try {
                        s.setTiengiam(Double.parseDouble(txtTiengiam.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Tiền giảm chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    
                    try {
                        s.setThanhtien(Double.parseDouble(txtThanhtien.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Thành tiền chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    
                    try {
                        s.setConno(Double.parseDouble(txtConno.getText()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Còn nợ chỉ là số ko phải là kí tự");
                        txtSodien.requestFocus();
                        isNXB=false;
                        return;                     
                    }
                    
                    String tt ="";
                        if(jRadioyes.isSelected()){
                            tt = "Đã thanh toán";
                    }else{
                        tt = "Chưa thanh toán";
                    }
                    s.setTinhtranghd(tt);
                   
                    checkmahoadon=new HoadondichvuDAO().CheckMahd(txtMahd.getText());
                 System.out.println("ArrayList: " + checkmahoadon);
                 System.err.println(tkquanlyhoadondichvu);
                    int size = checkmahoadon.size();
                    if(size== 0){
                   new HoadondichvuDAO().ThemHoadon(s);
                    showTable();
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    XoaTrang();
                    KhoaMo(true);
               }
                }else{

                    JOptionPane.showMessageDialog(rootPane, "Ngày lập phải nhỏ hơn hoặc bằng ngày hiện thời!");
                }

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng (vd: dd/MM/yyyy)!");

            }
            
            }
    }//GEN-LAST:event_btnGhiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoadondichvuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoadondichvuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoadondichvuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoadondichvuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoadondichvuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Banghienthi;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadiono;
    private javax.swing.JRadioButton jRadioyes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtConno;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMang;
    private javax.swing.JTextField txtMaphong;
    private javax.swing.JTextField txtNgaylap;
    private javax.swing.JTextField txtSodien;
    private javax.swing.JTextField txtSonuoc;
    private javax.swing.JTextField txtThanhtien;
    private javax.swing.JTextField txtTiendong;
    private javax.swing.JTextField txtTiengiam;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
     quanlyhoadondichvu=new HoadondichvuDAO().getListHoadon();
     model.setRowCount(0);
    DateFormat dateFormat = null;
    dateFormat = new SimpleDateFormat("dd/MM/yyyy");
     for(HoadondichvuModel s:quanlyhoadondichvu){
          System.err.println(s);
         model.addRow(new Object[]{
             Banghienthi.getRowCount()+1,s.getMahd(),s.getMaphong(),dateFormat.format(s.getNgaylap()),s.getSodien(),s.getSonuoc(),s.getMang(),s.getTiengiam(),s.getThanhtien(),s.getConno(),s.getTinhtranghd()
        });
         
     }
    
    }
    private void XoaTrang(){
        txtMahd.setText("");
        txtMaphong.setText("");
        
        txtNgaylap.setText("");
        
        txtSodien.setText("");
        txtSonuoc.setText("");
        txtMang.setText("");
        txtTiengiam.setText("");
        txtThanhtien.setText("");
        txtConno.setText("");
        jRadioyes.setSelected(true);
        txtTimkiem.setText("");
        
        showTable();
    }
    private void TinhTien(){
        double sodien= 0;
        double sonuoc= 0;
        double tienmang= 0;
        double tiengiam= 0;
        double tiendong= 0;
        double thanhtien= 0;
        double conno= 0;
        
        sodien= Double.parseDouble(txtSodien.getText());
        sonuoc= Double.parseDouble(txtSonuoc.getText());
        tiengiam= Double.parseDouble(txtTiengiam.getText());
        tienmang= Double.parseDouble(txtMang.getText());
        tiendong= Double.parseDouble(txtTiendong.getText());
        
        thanhtien= sodien*3000 +sonuoc*8000 +tienmang;
        conno=thanhtien-tiendong;
        
        txtThanhtien.setText(thanhtien+"");
         txtConno.setText(conno+"");
    }
    private  void TuTaoMa(){
        String m= HoadondichvuDAO.Taoma("hoadon", "Mahd");
        
        try {
            int matt=  Integer.parseInt(m);      
            txtMahd.setText(String.format("%06d", matt + 1));
        } catch(NumberFormatException e) {
            System.out.println("Khong the chuyen doi chuoi thanh so nguyen");
        }
    }
    public void KhoaMo(boolean b) {
        btnThem.setEnabled(b);
        btnGhi.setEnabled(!b);
        
        
    }
}
