/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.HopDongDAO;
import DAO.NhanvienDAO;
import DAO.PhongDAO;
import DAO.SinhvienDAO;
import Model.HopdongModel;
import Model.NhanvienModel;
import Model.SinhvienModel;
import Model.PhongModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamd
 */
public class HopdongView extends javax.swing.JFrame {

    
    int selectedIndex;
    int selectedIndexchung;
    public int edit;
    int delete;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private List<HopdongModel> quanlyhopdong;
    private List<HopdongModel> tkquanlyhopdong;
    private List<SinhvienModel> tkquanlysinhvien;
    private List<NhanvienModel> tkquanlynhanvien;
    private List<PhongModel> tkquanlyphong;
    private List<HopdongModel> checkmahopdong;
    private DefaultTableModel model;
    private DefaultTableModel modelchung;
    /**
     * Creates new form HopdongView
     */
    public HopdongView() {
        initComponents();
        KhoaMo(true);
        this.setLocationRelativeTo(null);
        model=(DefaultTableModel)Banghienthi.getModel();
        showTable();
        modelchung=(DefaultTableModel)Banghienthichung.getModel();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimkiemhd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Banghienthi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Banghienthichung = new javax.swing.JTable();
        txtTimkiemChung = new javax.swing.JTextField();
        jRadioNhanvien = new javax.swing.JRadioButton();
        jRadioSinhvien = new javax.swing.JRadioButton();
        jRadioPhong = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnTimkiemchung = new javax.swing.JButton();
        btnchon = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgaylap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayDen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNgaytra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTiencoc = new javax.swing.JTextField();
        txtHotenNV = new javax.swing.JTextField();
        txtMasv = new javax.swing.JTextField();
        txtMaphong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        txtHotenSV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTienphong = new javax.swing.JTextField();
        btnThemmoihd = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnKetthuc = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jComboTinhtrang = new javax.swing.JComboBox<>();
        btnTimkiemhd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hợp Đồng Sinh Viên");

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm:");

        txtTimkiemhd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Banghienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hợp đồng", "Mã nhân viên", "Mã phòng", "Mã sinh viên", "Ngày lập", "Ngày đến", "Ngày trả", "Tiền phòng", "Tiền cộc ", "Tình trạng"
            }
        ));
        Banghienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanghienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Banghienthi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tra cứu thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        Banghienthichung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "1", "2", "3"
            }
        ));
        Banghienthichung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanghienthichungMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Banghienthichung);

        txtTimkiemChung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(jRadioNhanvien);
        jRadioNhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioNhanvien.setText("Nhân viên");
        jRadioNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNhanvienActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSinhvien);
        jRadioSinhvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioSinhvien.setText("Sinh viên");
        jRadioSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSinhvienActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioPhong);
        jRadioPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioPhong.setText("Phòng");
        jRadioPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPhongActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm:");

        btnTimkiemchung.setBackground(new java.awt.Color(153, 255, 153));
        btnTimkiemchung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiemchung.setText("Tìm kiếm");
        btnTimkiemchung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemchungActionPerformed(evt);
            }
        });

        btnchon.setBackground(new java.awt.Color(255, 153, 153));
        btnchon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimkiemChung, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimkiemchung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnchon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioSinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimkiemChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btnTimkiemchung)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioNhanvien)
                    .addComponent(jRadioSinhvien)
                    .addComponent(jRadioPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số hợp đồng:");

        txtMahd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Người nhập:");

        txtManv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtManv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManvActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sinh viên:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tiền phòng:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày lập:");

        txtNgaylap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ngày đến:");

        txtNgayDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày trả:");

        txtNgaytra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tiền cọc:");

        txtTiencoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHotenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMasv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasvActionPerformed(evt);
            }
        });

        txtMaphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaphongActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Phòng:");

        txtMota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotaActionPerformed(evt);
            }
        });

        txtHotenSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHotenSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenSVActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tình trạng:");

        txtTienphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTienphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienphongActionPerformed(evt);
            }
        });

        btnThemmoihd.setBackground(new java.awt.Color(0, 204, 255));
        btnThemmoihd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemmoihd.setForeground(new java.awt.Color(255, 255, 255));
        btnThemmoihd.setText("Thêm hợp đồng mới");
        btnThemmoihd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoihdActionPerformed(evt);
            }
        });

        btnGhi.setBackground(new java.awt.Color(0, 153, 153));
        btnGhi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGhi.setForeground(new java.awt.Color(255, 255, 255));
        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnKetthuc.setBackground(new java.awt.Color(0, 0, 204));
        btnKetthuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKetthuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetthuc.setText("Kết thúc hợp đồng");
        btnKetthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetthucActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 51));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa hợp đồng");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 204, 51));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Kết thúc");

        jComboTinhtrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboTinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa kết thúc", "Đã kết thúc", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHotenNV))
                                    .addComponent(txtMahd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTienphong)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMasv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHotenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgaytra)
                                    .addComponent(txtNgayDen)
                                    .addComponent(txtTiencoc)
                                    .addComponent(txtNgaylap)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThoat))
                                    .addComponent(jComboTinhtrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThemmoihd)
                        .addGap(42, 42, 42)
                        .addComponent(btnGhi)
                        .addGap(40, 40, 40)
                        .addComponent(btnKetthuc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtHotenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHotenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNgaytra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTienphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGhi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(btnThemmoihd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKetthuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimkiemhd.setBackground(new java.awt.Color(0, 255, 204));
        btnTimkiemhd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiemhd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon-24.png"))); // NOI18N
        btnTimkiemhd.setText("Tìm kiếm");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Danh sách hợp đồng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiemhd, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimkiemhd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTimkiemhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimkiemhd))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1795, 1795, 1795)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasvActionPerformed

    private void txtMaphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaphongActionPerformed

    private void txtMotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotaActionPerformed

    private void txtTienphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienphongActionPerformed

    private void txtHotenSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenSVActionPerformed

    private void txtManvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManvActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         PhongModel p=new PhongModel();
         p.setMap(txtMaphong.getText());
         txtMahd.setEditable(true);
        delete=Banghienthi.getSelectedRow();
         HopdongModel s=quanlyhopdong.get(selectedIndex);
        if (quanlyhopdong.size() > 0) {
            if (delete!= -1) {
                int choic = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa?");
                if (choic == JOptionPane.YES_OPTION) {
                    new HopDongDAO().XoaHopdong(s.getMahd());
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    showTable();
                    XoaTrang();
                    new PhongDAO().SuaphongkhixoaHD(p);
                    bangphu();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã hủy");
                    XoaTrang();
                    showTable();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sách cần xóa");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKetthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetthucActionPerformed
        // TODO add your handling code here:
        PhongModel p=new PhongModel();
         p.setMap(txtMaphong.getText());
         txtMahd.setEditable(true);
        delete=Banghienthi.getSelectedRow();
         HopdongModel s=quanlyhopdong.get(selectedIndex);
        if (quanlyhopdong.size() > 0) {
            if (delete!= -1) {
                int choic = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn kết thúc?");
                if (choic == JOptionPane.YES_OPTION) {
                    new HopDongDAO().XoaHopdong(s.getMahd());
                    JOptionPane.showMessageDialog(rootPane, "Kết thúc thành công thành công");
                    showTable();
                    XoaTrang();
                    new PhongDAO().SuaphongkhixoaHD(p);
                    bangphu();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã hủy");
                    XoaTrang();
                    showTable();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sách cần kết thúc");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
    }//GEN-LAST:event_btnKetthucActionPerformed

    private void btnTimkiemchungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemchungActionPerformed
        // TODO add your handling code here:
        bangphu();
    }//GEN-LAST:event_btnTimkiemchungActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
         
            if(jRadioSinhvien.isSelected()){
               selectedIndexchung=Banghienthichung.getSelectedRow();
                SinhvienModel s= tkquanlysinhvien.get(selectedIndexchung);
        
                txtMasv.setText(s.getMasv());
                txtHotenSV.setText(s.getHoten());
                 System.out.println("ArrayList: " + tkquanlysinhvien);
                 System.err.println(tkquanlysinhvien);
                 return;
            }  
             if(jRadioNhanvien.isSelected()){
               selectedIndexchung=Banghienthichung.getSelectedRow();
                NhanvienModel s= tkquanlynhanvien.get(selectedIndexchung);
        
                txtManv.setText(s.getManv());
                txtHotenNV.setText(s.getHoten());
                 return;
            }  
              if(jRadioPhong.isSelected()){
               selectedIndexchung=Banghienthichung.getSelectedRow();
                PhongModel s= tkquanlyphong.get(selectedIndexchung);
                txtMaphong.setText(s.getMap());
                txtMota.setText(s.getMota());   
                 return;
            }  
            
        
    }//GEN-LAST:event_btnchonActionPerformed

    private void BanghienthichungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanghienthichungMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BanghienthichungMouseClicked

    private void jRadioNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNhanvienActionPerformed
        // TODO add your handling code here:
        bangphu();
    }//GEN-LAST:event_jRadioNhanvienActionPerformed

    private void jRadioSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSinhvienActionPerformed
        // TODO add your handling code here:
        bangphu();
    }//GEN-LAST:event_jRadioSinhvienActionPerformed

    private void jRadioPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPhongActionPerformed
        // TODO add your handling code here:
        bangphu();
    }//GEN-LAST:event_jRadioPhongActionPerformed

    private void btnThemmoihdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoihdActionPerformed
        // TODO add your handling code here:
        bangphu();
        KhoaMo(false);
        TuTaoMa();
        txtMasv.setText("");
        txtHotenSV.setText("");
        txtMaphong.setText("");
        txtMota.setText("");
    }//GEN-LAST:event_btnThemmoihdActionPerformed

    private void BanghienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanghienthiMouseClicked
        // TODO add your handling code here:
        KhoaMo(true);
        txtMahd.setEditable(false);
        selectedIndex=Banghienthi.getSelectedRow();
        HopdongModel p= quanlyhopdong.get(selectedIndex);
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtMahd.setText(p.getMahd());
        txtManv.setText(p.getManv());
         tkquanlynhanvien=new NhanvienDAO().Timkiem(p.getManv());
        for(NhanvienModel nv:tkquanlynhanvien){
           txtHotenNV.setText(nv.getHoten());
                 }
        
        txtMaphong.setText(p.getMap());
         tkquanlyphong=new PhongDAO().Timkiem(p.getMap());
        for(PhongModel mt:tkquanlyphong){
           txtMota.setText(mt.getMota());
                 }
        txtMasv.setText(p.getMasv());
        tkquanlysinhvien=new SinhvienDAO().Timkiem(p.getMasv());
        for(SinhvienModel sv:tkquanlysinhvien){
           txtHotenSV.setText(sv.getHoten());
                 }
        txtTienphong.setText(Math.round(p.getTienphong())+"");
        txtTiencoc.setText(Math.round(p.getTiencoc())+"");
        txtNgaylap.setText(dateFormat.format(p.getNgaylap()));
        txtNgayDen.setText(dateFormat.format(p.getNgayden()));
        txtNgaytra.setText(dateFormat.format(p.getNgaytra()));
      
       jComboTinhtrang.setSelectedItem(p.getTinhtrang());
    }//GEN-LAST:event_BanghienthiMouseClicked

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        
       if(txtManv.getText().isEmpty() || txtHotenNV.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn nhân viên trong bảng nhân viên bên tay trái");
              txtManv.requestFocus();
              return;
        }
      
        if(txtMaphong.getText().isEmpty() || txtMota.getText().isEmpty() ){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn phòng trong bảng phòng bên tay trái");
             txtMaphong.requestFocus();
              return;
        }
        if(txtMasv.getText().isEmpty()||txtHotenSV.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn sinh viên trong bảng sinh viên viên bên tay trái");
             txtMasv.requestFocus();
              return;
        }
        if(txtTienphong.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập tiền phòng ");
             txtTienphong.requestFocus();
              return;
        }
        if(txtNgaylap.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập ngày lập");
             txtNgaylap.requestFocus();
              return;
        }
        if(txtNgayDen.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập ngày đến");
             txtNgayDen.requestFocus();
              return;
        }
        if(txtNgaytra.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập ngày trả");
             txtNgaytra.requestFocus();
              return;
        }
        
        try {
            HopdongModel hd=new HopdongModel();
            Date dateNow = new Date();
            Date nl,nd,nt;
            nl = df.parse(txtNgaylap.getText());
            nd = df.parse(txtNgayDen.getText());
            nt = df.parse(txtNgaytra.getText());
             if(nl.getTime() <= dateNow.getTime()){
                hd.setMahd(txtMahd.getText());
                hd.setManv(txtManv.getText());
                hd.setMap(txtMaphong.getText());
                hd.setMasv(txtMasv.getText());
                hd.setNgaylap(nl);
                hd.setNgayden(nd);
                hd.setNgaytra(nt);
                
             
                hd.setTinhtrang(jComboTinhtrang.getSelectedItem().toString());
                boolean isNXB=true;
                try {
                        hd.setTienphong(Double.parseDouble(txtTienphong.getText()));

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Giá tiền chỉ là số ko phải là kí tự");
                        txtTienphong.requestFocus();
                        isNXB=false;
                        return;
                       
                    }
                
                try {
                          hd.setTiencoc(Double.parseDouble(txtTiencoc.getText()));

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Số người ở hiện tại chỉ là số ko phải là kí tự");
                        txtTiencoc.requestFocus();
                        isNXB=false;
                        return;
                    }
                PhongModel p=new PhongModel();
               p.setMap(txtMaphong.getText());
               if(isNXB){
                   new HopDongDAO().ThemHopdong(hd);
                    showTable();
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    new PhongDAO().SuaphongkhithemHD(p);
                    XoaTrang();
                    KhoaMo(true);
                    bangphu();
               }
            }else{
                
                JOptionPane.showMessageDialog(rootPane, "Ngày sinh phải nhỏ hơn hoặc bằng ngày hiện thời!");
                }
            
        } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạng (vd: dd/MM/yyyy)!");

        }
        
    }//GEN-LAST:event_btnGhiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HopdongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HopdongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HopdongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HopdongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HopdongView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Banghienthi;
    private javax.swing.JTable Banghienthichung;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnKetthuc;
    private javax.swing.JButton btnThemmoihd;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiemchung;
    private javax.swing.JButton btnTimkiemhd;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnchon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboTinhtrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioNhanvien;
    private javax.swing.JRadioButton jRadioPhong;
    private javax.swing.JRadioButton jRadioSinhvien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtHotenNV;
    private javax.swing.JTextField txtHotenSV;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtMaphong;
    private javax.swing.JTextField txtMasv;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgaylap;
    private javax.swing.JTextField txtNgaytra;
    private javax.swing.JTextField txtTiencoc;
    private javax.swing.JTextField txtTienphong;
    private javax.swing.JTextField txtTimkiemChung;
    private javax.swing.JTextField txtTimkiemhd;
    // End of variables declaration//GEN-END:variables

    
    private void bangphu(){
    
        if(jRadioSinhvien.isSelected()){
            String tksv=txtTimkiemChung.getText();
                 tkquanlysinhvien=new SinhvienDAO().TimkiemSV(tksv);
                 modelchung.setRowCount(0);
                 for(SinhvienModel s:tkquanlysinhvien){
                        modelchung.addRow(new Object[]{
                       Banghienthichung.getRowCount()+1,s.getMasv(),s.getHoten(),
                     });
                 }
                 return;
            
        }
        if(jRadioNhanvien.isSelected()){
            String tksv=txtTimkiemChung.getText();
                 tkquanlynhanvien=new NhanvienDAO().Timkiem(tksv);
                 modelchung.setRowCount(0);
                 for(NhanvienModel nv:tkquanlynhanvien){
                        modelchung.addRow(new Object[]{
                       Banghienthichung.getRowCount()+1,nv.getManv(),nv.getHoten(),
                     });
                 }
                 return;
            
        }
        if(jRadioPhong.isSelected()){
            String tksv=txtTimkiemChung.getText();
                 tkquanlyphong=new PhongDAO().TimkiemPhong(tksv);
                 modelchung.setRowCount(0);
                 for(PhongModel s:tkquanlyphong){
                        modelchung.addRow(new Object[]{
                      s.getMap(),s.getLoaiphong(),s.getMota(),
                     });
                 }
                 return;
            
        }
    }
    
    
     private void showTable() {
     quanlyhopdong=new HopDongDAO().getListHopdong();
     model.setRowCount(0);
    DateFormat dateFormat = null;
    dateFormat = new SimpleDateFormat("dd/MM/yyyy");
     for(HopdongModel s:quanlyhopdong){
          System.err.println(s);
         model.addRow(new Object[]{
             Banghienthi.getRowCount()+1,s.getMahd(),s.getManv(),s.getMap(),s.getMasv(),dateFormat.format(s.getNgaylap()),dateFormat.format(s.getNgayden()),dateFormat.format(s.getNgaytra()), (int)s.getTienphong(),(int)s.getTiencoc(),s.getTinhtrang(),
             
        });
         
     }
    
    }
    private void XoaTrang(){
        txtMahd.setText("");
        txtManv.setText("");
        txtMasv.setText("");
        txtHotenNV.setText("");
        txtHotenSV.setText("");
        txtMaphong.setText("");
        txtMota.setText("");
        txtNgaylap.setText("");
        txtNgayDen.setText("");
        txtNgaylap.setText("");
        txtTiencoc.setText("");
        txtTienphong.setText("");
       jComboTinhtrang.setSelectedIndex(0);
        showTable();
    }
     private  void TuTaoMa(){
        String m= HopDongDAO.Taoma("hopdong", "Mahd");
        
        try {
            int matt=  Integer.parseInt(m);      
            txtMahd.setText(String.format("%06d", matt + 1));
        } catch(NumberFormatException e) {
            System.out.println("Khong the chuyen doi chuoi thanh so nguyen");
        }
    }
      public void KhoaMo(boolean b) {
        btnThemmoihd.setEnabled(b);
        btnGhi.setEnabled(!b);
        btnKetthuc.setEnabled(b);
        btnXoa.setEnabled(b);
        btnchon.setEnabled(!b);
       
        
        
    }
}
