/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author phamd
 */
public class TrangchuView extends javax.swing.JFrame {

    /**
     * Creates new form TrangchuView
     */
    public TrangchuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_DieuKhien_317 = new javax.swing.JPanel();
        jlb_TrangChu_317 = new javax.swing.JLabel();
        jlb_phong_317 = new javax.swing.JLabel();
        jlb_ThongKe_317 = new javax.swing.JLabel();
        Name_KTX_317 = new javax.swing.JLabel();
        jSeparator1_317 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1_QuanLySinhVien = new javax.swing.JPanel();
        jLabel2_qlsv_317 = new javax.swing.JLabel();
        icon_qlsv_318 = new javax.swing.JLabel();
        jPanel2_DangKiKTX = new javax.swing.JPanel();
        jLabel2_dkktx_317 = new javax.swing.JLabel();
        icon_dkktx_317 = new javax.swing.JLabel();
        jPanel3_QuanLyPhongKTX = new javax.swing.JPanel();
        jLabel2_qlpktx_317 = new javax.swing.JLabel();
        jLabel4_icon_qlpktx_317 = new javax.swing.JLabel();
        jPanel4_ThongKe = new javax.swing.JPanel();
        jLabel2_tk_317 = new javax.swing.JLabel();
        jLabel8_icon_tk_317 = new javax.swing.JLabel();
        jPanel5_QuanLyDienNuoc = new javax.swing.JPanel();
        jLabel2_tp_317 = new javax.swing.JLabel();
        jLabel7_icon_tp_317 = new javax.swing.JLabel();
        jPanel1_QuanLyHoaDonPhong = new javax.swing.JPanel();
        jLabel1_qlnx_317 = new javax.swing.JLabel();
        jLabel6_icon_qlnx_317 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_DieuKhien_317.setBackground(new java.awt.Color(54, 33, 89));

        jlb_TrangChu_317.setBackground(new java.awt.Color(64, 43, 100));
        jlb_TrangChu_317.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlb_TrangChu_317.setForeground(new java.awt.Color(255, 255, 255));
        jlb_TrangChu_317.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlb_TrangChu_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/go_home_icon_181144.png"))); // NOI18N
        jlb_TrangChu_317.setText("        Trang Chủ");
        jlb_TrangChu_317.setOpaque(true);
        jlb_TrangChu_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_TrangChu_317MouseClicked(evt);
            }
        });

        jlb_phong_317.setBackground(new java.awt.Color(64, 43, 100));
        jlb_phong_317.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlb_phong_317.setForeground(new java.awt.Color(255, 255, 255));
        jlb_phong_317.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlb_phong_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/caiDat.png"))); // NOI18N
        jlb_phong_317.setText("    Quản lý tài khoản");
        jlb_phong_317.setOpaque(true);
        jlb_phong_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_phong_317MouseClicked(evt);
            }
        });

        jlb_ThongKe_317.setBackground(new java.awt.Color(64, 43, 100));
        jlb_ThongKe_317.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlb_ThongKe_317.setForeground(new java.awt.Color(255, 255, 255));
        jlb_ThongKe_317.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlb_ThongKe_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/system_log_out_icon_181207.png"))); // NOI18N
        jlb_ThongKe_317.setText("       Đăng Xuất");
        jlb_ThongKe_317.setOpaque(true);
        jlb_ThongKe_317.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb_ThongKe_317MouseClicked(evt);
            }
        });

        Name_KTX_317.setBackground(new java.awt.Color(255, 255, 255));
        Name_KTX_317.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Name_KTX_317.setForeground(new java.awt.Color(255, 255, 255));
        Name_KTX_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_KTX_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logotruong.png"))); // NOI18N
        Name_KTX_317.setText("Quản Lý Ký Túc Xá");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facebook.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/youtube.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/twitter.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jpn_DieuKhien_317Layout = new javax.swing.GroupLayout(jpn_DieuKhien_317);
        jpn_DieuKhien_317.setLayout(jpn_DieuKhien_317Layout);
        jpn_DieuKhien_317Layout.setHorizontalGroup(
            jpn_DieuKhien_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_DieuKhien_317Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_DieuKhien_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_ThongKe_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb_phong_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb_TrangChu_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jpn_DieuKhien_317Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1_317)
                .addGap(20, 20, 20))
            .addGroup(jpn_DieuKhien_317Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Name_KTX_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_DieuKhien_317Layout.setVerticalGroup(
            jpn_DieuKhien_317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_DieuKhien_317Layout.createSequentialGroup()
                .addComponent(Name_KTX_317, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1_317, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jlb_TrangChu_317, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_phong_317, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_ThongKe_317, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1_QuanLySinhVien.setBackground(new java.awt.Color(121, 130, 222));
        jPanel1_QuanLySinhVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1_QuanLySinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1_QuanLySinhVienMouseClicked(evt);
            }
        });

        jLabel2_qlsv_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_qlsv_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_qlsv_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_qlsv_317.setText("QUẢN LÝ SINH VIÊN");
        jLabel2_qlsv_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon_qlsv_318.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_qlsv_318.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/management_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1_QuanLySinhVienLayout = new javax.swing.GroupLayout(jPanel1_QuanLySinhVien);
        jPanel1_QuanLySinhVien.setLayout(jPanel1_QuanLySinhVienLayout);
        jPanel1_QuanLySinhVienLayout.setHorizontalGroup(
            jPanel1_QuanLySinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_qlsv_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1_QuanLySinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_qlsv_318, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1_QuanLySinhVienLayout.setVerticalGroup(
            jPanel1_QuanLySinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_QuanLySinhVienLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(icon_qlsv_318)
                .addGap(18, 18, 18)
                .addComponent(jLabel2_qlsv_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2_DangKiKTX.setBackground(new java.awt.Color(121, 130, 222));
        jPanel2_DangKiKTX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2_DangKiKTX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2_DangKiKTXMouseClicked(evt);
            }
        });

        jLabel2_dkktx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_dkktx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_dkktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_dkktx_317.setText("QUẢN LÝ NHÂN VIÊN");
        jLabel2_dkktx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon_dkktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_dkktx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_registration_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2_DangKiKTXLayout = new javax.swing.GroupLayout(jPanel2_DangKiKTX);
        jPanel2_DangKiKTX.setLayout(jPanel2_DangKiKTXLayout);
        jPanel2_DangKiKTXLayout.setHorizontalGroup(
            jPanel2_DangKiKTXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_DangKiKTXLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(icon_dkktx_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addComponent(jLabel2_dkktx_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2_DangKiKTXLayout.setVerticalGroup(
            jPanel2_DangKiKTXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_DangKiKTXLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(icon_dkktx_317)
                .addGap(0, 0, 0)
                .addComponent(jLabel2_dkktx_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3_QuanLyPhongKTX.setBackground(new java.awt.Color(121, 130, 222));
        jPanel3_QuanLyPhongKTX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3_QuanLyPhongKTX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3_QuanLyPhongKTXMouseClicked(evt);
            }
        });

        jLabel2_qlpktx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_qlpktx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_qlpktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_qlpktx_317.setText("QUẢN LÝ PHÒNG KTX");
        jLabel2_qlpktx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4_icon_qlpktx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_icon_qlpktx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bunk_bed_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3_QuanLyPhongKTXLayout = new javax.swing.GroupLayout(jPanel3_QuanLyPhongKTX);
        jPanel3_QuanLyPhongKTX.setLayout(jPanel3_QuanLyPhongKTXLayout);
        jPanel3_QuanLyPhongKTXLayout.setHorizontalGroup(
            jPanel3_QuanLyPhongKTXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_QuanLyPhongKTXLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4_icon_qlpktx_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addComponent(jLabel2_qlpktx_317, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3_QuanLyPhongKTXLayout.setVerticalGroup(
            jPanel3_QuanLyPhongKTXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3_QuanLyPhongKTXLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4_icon_qlpktx_317)
                .addGap(0, 0, 0)
                .addComponent(jLabel2_qlpktx_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4_ThongKe.setBackground(new java.awt.Color(121, 130, 222));
        jPanel4_ThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4_ThongKeMouseClicked(evt);
            }
        });

        jLabel2_tk_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_tk_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_tk_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_tk_317.setText("QUẢN LÝ HƠP ĐỒNG");
        jLabel2_tk_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8_icon_tk_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8_icon_tk_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/statistics_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4_ThongKeLayout = new javax.swing.GroupLayout(jPanel4_ThongKe);
        jPanel4_ThongKe.setLayout(jPanel4_ThongKeLayout);
        jPanel4_ThongKeLayout.setHorizontalGroup(
            jPanel4_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_ThongKeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel8_icon_tk_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addComponent(jLabel2_tk_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4_ThongKeLayout.setVerticalGroup(
            jPanel4_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_ThongKeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8_icon_tk_317)
                .addGap(0, 0, 0)
                .addComponent(jLabel2_tk_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5_QuanLyDienNuoc.setBackground(new java.awt.Color(121, 130, 222));
        jPanel5_QuanLyDienNuoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5_QuanLyDienNuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5_QuanLyDienNuocMouseClicked(evt);
            }
        });

        jLabel2_tp_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2_tp_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_tp_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_tp_317.setText("QUẢN LÝ ĐIỆN NƯỚC");
        jLabel2_tp_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7_icon_tp_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7_icon_tp_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expensive_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5_QuanLyDienNuocLayout = new javax.swing.GroupLayout(jPanel5_QuanLyDienNuoc);
        jPanel5_QuanLyDienNuoc.setLayout(jPanel5_QuanLyDienNuocLayout);
        jPanel5_QuanLyDienNuocLayout.setHorizontalGroup(
            jPanel5_QuanLyDienNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_QuanLyDienNuocLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7_icon_tp_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addComponent(jLabel2_tp_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5_QuanLyDienNuocLayout.setVerticalGroup(
            jPanel5_QuanLyDienNuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_QuanLyDienNuocLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7_icon_tp_317)
                .addGap(0, 0, 0)
                .addComponent(jLabel2_tp_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1_QuanLyHoaDonPhong.setBackground(new java.awt.Color(121, 130, 222));
        jPanel1_QuanLyHoaDonPhong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1_QuanLyHoaDonPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1_QuanLyHoaDonPhongMouseClicked(evt);
            }
        });

        jLabel1_qlnx_317.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1_qlnx_317.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_qlnx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_qlnx_317.setText("QUẢN LÝ HÓA ĐƠN PHÒNG");
        jLabel1_qlnx_317.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6_icon_qlnx_317.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_icon_qlnx_317.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/garage_64px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1_QuanLyHoaDonPhongLayout = new javax.swing.GroupLayout(jPanel1_QuanLyHoaDonPhong);
        jPanel1_QuanLyHoaDonPhong.setLayout(jPanel1_QuanLyHoaDonPhongLayout);
        jPanel1_QuanLyHoaDonPhongLayout.setHorizontalGroup(
            jPanel1_QuanLyHoaDonPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_QuanLyHoaDonPhongLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6_icon_qlnx_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
            .addComponent(jLabel1_qlnx_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1_QuanLyHoaDonPhongLayout.setVerticalGroup(
            jPanel1_QuanLyHoaDonPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_QuanLyHoaDonPhongLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6_icon_qlnx_317)
                .addGap(0, 0, 0)
                .addComponent(jLabel1_qlnx_317, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_QuanLySinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2_DangKiKTX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5_QuanLyDienNuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3_QuanLyPhongKTX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_QuanLyHoaDonPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2_DangKiKTX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_QuanLySinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3_QuanLyPhongKTX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4_ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5_QuanLyDienNuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1_QuanLyHoaDonPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpn_DieuKhien_317, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_DieuKhien_317, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jlb_ThongKe_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_ThongKe_317MouseClicked

         this.dispose();
        DangnhapView dangnhapView=new DangnhapView();
            dangnhapView.show();
    }//GEN-LAST:event_jlb_ThongKe_317MouseClicked

    private void jlb_phong_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_phong_317MouseClicked

        this.dispose();
        TaikhoanView taikhoanView=new TaikhoanView();
            taikhoanView.show();
    }//GEN-LAST:event_jlb_phong_317MouseClicked

    private void jlb_TrangChu_317MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb_TrangChu_317MouseClicked

    }//GEN-LAST:event_jlb_TrangChu_317MouseClicked

    private void jPanel1_QuanLySinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1_QuanLySinhVienMouseClicked
        this.dispose();
        SinhvienView sinhvienView=new SinhvienView();
            sinhvienView.show();
    }//GEN-LAST:event_jPanel1_QuanLySinhVienMouseClicked

    private void jPanel2_DangKiKTXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2_DangKiKTXMouseClicked
         this.dispose();
        NhanvienView nhanvienView=new NhanvienView();
            nhanvienView.show();
    }//GEN-LAST:event_jPanel2_DangKiKTXMouseClicked

    private void jPanel3_QuanLyPhongKTXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_QuanLyPhongKTXMouseClicked

    }//GEN-LAST:event_jPanel3_QuanLyPhongKTXMouseClicked

    private void jPanel4_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4_ThongKeMouseClicked

    }//GEN-LAST:event_jPanel4_ThongKeMouseClicked

    private void jPanel5_QuanLyDienNuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5_QuanLyDienNuocMouseClicked

    }//GEN-LAST:event_jPanel5_QuanLyDienNuocMouseClicked

    private void jPanel1_QuanLyHoaDonPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1_QuanLyHoaDonPhongMouseClicked
            this.dispose();
        HoadonphongView hoadonphongView=new HoadonphongView();
            hoadonphongView.show();
    }//GEN-LAST:event_jPanel1_QuanLyHoaDonPhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangchuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangchuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangchuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangchuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangchuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name_KTX_317;
    private javax.swing.JLabel icon_dkktx_317;
    private javax.swing.JLabel icon_qlsv_318;
    private javax.swing.JLabel jLabel1_qlnx_317;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_dkktx_317;
    private javax.swing.JLabel jLabel2_qlpktx_317;
    private javax.swing.JLabel jLabel2_qlsv_317;
    private javax.swing.JLabel jLabel2_tk_317;
    private javax.swing.JLabel jLabel2_tp_317;
    private javax.swing.JLabel jLabel4_icon_qlpktx_317;
    private javax.swing.JLabel jLabel6_icon_qlnx_317;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_icon_tp_317;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_icon_tk_317;
    private javax.swing.JPanel jPanel1_QuanLyHoaDonPhong;
    private javax.swing.JPanel jPanel1_QuanLySinhVien;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2_DangKiKTX;
    private javax.swing.JPanel jPanel3_QuanLyPhongKTX;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel4_ThongKe;
    private javax.swing.JPanel jPanel5_QuanLyDienNuoc;
    private javax.swing.JSeparator jSeparator1_317;
    private javax.swing.JLabel jlb_ThongKe_317;
    private javax.swing.JLabel jlb_TrangChu_317;
    private javax.swing.JLabel jlb_phong_317;
    private javax.swing.JPanel jpn_DieuKhien_317;
    // End of variables declaration//GEN-END:variables
}
